import os
from datetime import datetime

print("Script started")
api_key = os.getenv('NEWSAPI_KEY')
print(f"API Key set: {bool(api_key)}")
import os
import requests
from datetime import datetime

# Get API key
api_key = os.getenv('NEWSAPI_KEY')
print(f"API Key loaded: {bool(api_key)}")

if not api_key:
        print("Error: NEWSAPI_KEY not set")
        exit(1)

# NewsAPI configuration
BASE_URL = 'https://newsapi.org/v2/everything'
QUERIES = [
        '스타트업 발굴',  # Startup discovery
        '청년 취업 정책',  # Youth employment policy
        'AI 트렌드'  # AI trends
]

def fetch_news(query):
        """Fetch news for a given query."""
        params = {
                    'q': query,
                    'sortBy': 'publishedAt',
                    'language': 'ko',
                    'pageSize': 10,
                    'apiKey': api_key
        }

    try:
                response = requests.get(BASE_URL, params=params)
                response.raise_for_status()
                return response.json()
    except Exception as e:
                print(f"Error fetching news for '{query}': {e}")
                return {'articles': []}

def format_articles_to_markdown(articles, category):
        """Format articles into markdown."""
        md_text = f"## {category}\n\n"

    for article in articles[:5]:  # Top 5 articles
                title = article.get('title', 'No title')
                url = article.get('url', '#')
                source = article.get('source', {}).get('name', 'Unknown')
                published_at = article.get('publishedAt', '').split('T')[0]

        md_text += f"- **[{title}]({url})**\n"
        md_text += f"  - Source: {source} | Date: {published_at}\n\n"

    return md_text

# Fetch news for each query
print("Fetching news...")
all_news = {}
for query in QUERIES:
        news_data = fetch_news(query)
        all_news[query] = news_data.get('articles', [])

# Create markdown file
filename = f"news_{datetime.now().strftime('%Y-%m-%d')}.md"
print(f"Creating file: {filename}")

with open(filename, 'w', encoding='utf-8') as f:
        f.write(f"# Daily News - {datetime.now().strftime('%Y-%m-%d')}\n\n")

    for query in QUERIES:
                articles = all_news.get(query, [])
                if articles:
                                f.write(format_articles_to_markdown(articles, query))

    f.write("\n*Generated by GitHub Actions*\n")

print(f"News file created successfully: {filename}")
filename = f"news_{datetime.now().strftime('%Y-%m-%d')}.md"
with open(filename, 'w') as f:
    f.write(f"# Daily News - {datetime.now().strftime('%Y-%m-%d')}\n")
    f.write("Successfully created!\n")

print(f"File created: {filename}")
